# This is a basic workflow to help you get started with Actions

name: Deploy

# Run on main branch only
on:
  push:
    branches:
      - main



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: docs
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          use-mamba: true
      
      - name: Build documentation
        run: make html
        
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          # Only keep the latest commit to avoid bloating the repository
          force_orphan: true
          cname: docs.xumijian.me
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
